# Generated by Django 2.1.5 on 2019-05-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
